version: '3.8'

services:

  shared-logging-builder:
    build:
      context: ./shared-logging
    container_name: shared-logging-builder
    volumes:
      - maven-repo:/root/.m2
    command: mvn clean install -DskipTests

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_REPO=https://github.com/BenAliHamza/repo-config
    networks:
      - micro-network

  studio-db:
    image: mysql:8.0
    container_name: studio-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studiodb
    ports:
      - "3307:3306"
    volumes:
      - studio-db-data:/var/lib/mysql
    networks:
      - micro-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  studio-service:
    build:
      context: ./studio
    container_name: studio-service
    depends_on:
      shared-logging-builder:
        condition: service_completed_successfully
      config-server:
        condition: service_started
      studio-db:
        condition: service_healthy
    volumes:
      - ./logs/studio:/logs
      - ./config-repo:/config-repo
      - maven-repo:/root/.m2
    ports:
      - "8081:8081"
    environment:
      LOG_DIR: /logs
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: default
    networks:
      - micro-network

  film-db:
    image: mongo:5.0
    container_name: film-db
    ports:
      - "27017:27017"
    volumes:
      - film-db-data:/data/db
    networks:
      - micro-network

  film-service:
    build:
      context: ./films
    container_name: film-service
    depends_on:
      shared-logging-builder:
        condition: service_completed_successfully
      film-db:
        condition: service_started
      config-server:
        condition: service_started
    volumes:
      - ./logs/films:/logs
      - ./config-repo:/config-repo
      - maven-repo:/root/.m2
    ports:
      - "8082:8082"
    environment:
      LOG_DIR: /logs
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: default
    networks:
      - micro-network

volumes:
  studio-db-data:
  film-db-data:
  maven-repo:

networks:
  micro-network:
